#!/usr/bin/env bash
threshold=350
synopsis=
index=0
html=$(cmark --nobreaks "$1")
while :; do
	index=$((index + 1))
	newSynopsis=$synopsis
	newSynopsis+=$(htmlq "body > *:nth-child(${index})" <<< "${html}")
	newSynopsis+=$'\n'
	if (( ${#synopsis} == 0 || ${#newSynopsis} < threshold )); then
		synopsis=$newSynopsis
	else
		break
	fi
done
echo -n "$synopsis"
