#!/usr/bin/env bash
threshold=150
synopsis=
index=0
html=$(cmark --nobreaks "$1")
while (( ${#synopsis} < threshold )); do
	index=$((index + 1))
	synopsis+=$(htmlq "body > *:nth-child(${index})" <<< "${html}")
	synopsis+=$'\n'
done
echo -n "$synopsis"
