#!/usr/bin/env bash
trimPunct() {
	declare -n v="$1"
	for punct in "${@:2}"; do
		if [[ "${v%%"${punct}"*}" != "${v}" ]]; then
			v="${v%%"${punct}"*}${punct}"
		fi
	done
}

html=$(cmark --nobreaks "$1")

text=$(htmlq -t "body > h1" <<< "${html}")
if [[ "$text" != "" ]]; then
	echo "$text"
	exit 0
fi

text=$(htmlq -t 'body > *:first-child' <<< "${html}")
trimPunct text "." "!" "?"
echo "$text"
